[versions]
fabric_api = "0.145.4+26.1.1"
fabric_loader = "0.18.6"
minecraft = "26.1.1"
modonomicon="1.132.3"

[libraries]
fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
modonomicon = { module = "com.klikli_dev:modonomicon-26.1.1-fabric", version.ref = "modonomicon" }

[bundles]
dev_mods = []
dependencies = [ "modonomicon" ]

[plugins]
fabric_loom = { id = "net.fabricmc.fabric-loom", version = "1.16-SNAPSHOT" }
pkpcpbp = { id = "at.petra-k.pkpcpbp.PKJson5Plugin", version = "0.2.0-pre-95" }